# Generated by Django 5.1.7 on 2025-04-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_caretaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image_url',
            field=models.FileField(upload_to='Media'),
        ),
    ]
