# Generated by Django 5.1.7 on 2025-04-13 11:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_animal_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image_url',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
