# Generated by Django 5.1.7 on 2025-04-13 12:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_image_url_animal_image_remove_event_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='proof_url',
        ),
        migrations.AddField(
            model_name='task',
            name='proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
