# Generated by Django 5.1.7 on 2025-04-13 12:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_task_proof_url_task_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='media_url',
        ),
        migrations.AddField(
            model_name='content',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
