# Generated by Django 5.1.7 on 2025-04-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_content_media_url_content_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='created_by',
        ),
    ]
