# Generated by Django 5.1.7 on 2025-04-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_content_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='proof',
        ),
        migrations.AddField(
            model_name='task',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
