# Generated by Django 5.1.7 on 2025-04-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_task_proof_task_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
