# Generated by Django 6.0 on 2025-12-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_task_deadline_alter_task_date_assigned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_assigned']},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'deadline'], name='api_task_status_056501_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['caretaker', 'status'], name='api_task_caretak_43120c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-date_assigned'], name='api_task_date_as_e08595_idx'),
        ),
    ]
